name: score_slam_basketball_points_counter_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21




flutter_native_splash:
  color: "#9EC8B9"
  image: assets/splash_screen.png
  android_12:
    image: assets/splash_screen.png
    color: "#9EC8B9"


flutter:


  uses-material-design: true

  assets:
    - assets/

